"""Texts written into the report document, per report language."""

LANGUAGES = {"tr": "Türkçe", "en": "English"}

TEXTS = {
    "tr": {
        "default_title": "Test Verileri Analiz Raporu",
        "project": "Proje",
        "prepared_by": "Hazırlayan",
        "date": "Tarih",
        "data_file": "Veri dosyası",
        "range": "Analiz aralığı",
        "cursor_range": "imleç aralığı",
        "all_data": "tüm veri",
        "no_data_in_range": "Aralıkta veri yok",
        "contents": "İçindekiler",
        "toc_hint": "İçindekiler tablosunu güncellemek için sağ tıklayıp \"Alanı Güncelleştir\" seçin.",
        "summary": "Özet",
        "duration": "Süre",
        "samples_in_range": "Aralıktaki örnek sayısı",
        "sample_rate": "Örnekleme hızı",
        "params_in_file": "Dosyadaki parametre sayısı",
        "params_in_report": "Rapordaki parametre sayısı",
        "report_contains": "Bu rapor şu bölümleri içerir: {sections}.",
        "notes": "Notlar",
        "statistics": "İstatistikler",
        "stats_table": "Analiz aralığındaki istatistikler",
        "no_data_for": "Aralıkta verisi olmayan parametreler: {names}.",
        "h_parameter": "Parametre",
        "h_samples": "Örnek",
        "h_min": "Min",
        "h_mean": "Ortalama",
        "h_max": "Maks",
        "h_std": "Std. sapma",
        "h_rms": "RMS",
        "op_missing": "Çalışma noktaları: '{param}' veya seçili parametrelerden biri için aralıkta veri yok.",
        "op_intro": "Çalışma noktaları: |{param} − değer| ≤ {tol} olan satırlar{conditions}.",
        "op_and": " ve ",
        "op_means": "Çalışma noktalarına göre ortalama değerler ({param})",
        "op_detail": "{label} noktasındaki istatistikler ({count} örnek)",
        "op_empty": "{param} ≈ {values} için örnek bulunamadı.",
        "trends": "Trend Grafikleri",
        "vs": "{y} – {x}",
        "time": "Zaman",
        "not_drawn": "Aralıkta veri olmadığı için çizilmeyen grafikler: {titles}.",
        "distributions": "Dağılımlar",
        "hist_caption": "{name} — ortalama {mean}, std. sapma {std}, min {min}, maks {max}, {count} örnek",
        "axis_time_s": "Zaman (s)",
        "axis_time_utc": "Zaman (UTC)",
        "axis_samples": "Örnek sayısı",
        "mean": "ortalama",
        "figure": "Şekil",
        "table": "Tablo",
        "page": "Sayfa",
    },
    "en": {
        "default_title": "Test Data Analysis Report",
        "project": "Project",
        "prepared_by": "Prepared by",
        "date": "Date",
        "data_file": "Data file",
        "range": "Analysed range",
        "cursor_range": "cursor range",
        "all_data": "all data",
        "no_data_in_range": "No data in range",
        "contents": "Contents",
        "toc_hint": "Right-click and choose \"Update Field\" to update the table of contents.",
        "summary": "Summary",
        "duration": "Duration",
        "samples_in_range": "Samples in range",
        "sample_rate": "Sample rate",
        "params_in_file": "Parameters in file",
        "params_in_report": "Parameters in report",
        "report_contains": "This report contains: {sections}.",
        "notes": "Notes",
        "statistics": "Statistics",
        "stats_table": "Statistics over the analysed range",
        "no_data_for": "No data in range for: {names}.",
        "h_parameter": "Parameter",
        "h_samples": "Samples",
        "h_min": "Min",
        "h_mean": "Mean",
        "h_max": "Max",
        "h_std": "Std. dev.",
        "h_rms": "RMS",
        "op_missing": "Operating points: '{param}' or a selected parameter has no data in range.",
        "op_intro": "Operating points: rows where |{param} − value| ≤ {tol}{conditions}.",
        "op_and": " and ",
        "op_means": "Mean values per operating point of {param}",
        "op_detail": "Statistics at {label} ({count} samples)",
        "op_empty": "No samples at {param} ≈ {values}.",
        "trends": "Trends",
        "vs": "{y} vs {x}",
        "time": "Time",
        "not_drawn": "Not drawn (no data in range): {titles}.",
        "distributions": "Distributions",
        "hist_caption": "{name} — mean {mean}, std. dev. {std}, min {min}, max {max}, {count} samples",
        "axis_time_s": "Time (s)",
        "axis_time_utc": "Time (UTC)",
        "axis_samples": "Samples",
        "mean": "mean",
        "figure": "Figure",
        "table": "Table",
        "page": "Page",
    },
}


def texts(language: str) -> dict:
    return TEXTS.get(language, TEXTS["tr"])
